### ISSUE TITLE
OrTools: label[i] not in pred

### ISSUE THREAD

**Issue by jiaziying** [wenhaomin/LaDe#4]
Hi, when I try to reproduce the route prediction using your code, I always get the following output and error for OrTools. 

[warning]: wrong in calculate KRC
[17, 13, 14, 6, 16, 3, 17]
[17, 5, 3]

Traceback (most recent call last):
  File "/home/LaDe-master/route_prediction/run.py", line 84, in <module>
    run(p)
  File "/home/LaDe-master/route_prediction/run.py", line 12, in run
    main(params)
  File "/home/LaDe-master/route_prediction/algorithm/basic/basic_model.py", line 335, in main
    result_dict = test_model(model, test_loader, device, params)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/LaDe-master/route_prediction/algorithm/basic/basic_model.py", line 281, in test_model
    e.update(pred, label, label_len, pred_len)
  File "/home/LaDe-master/route_prediction/utils/eval.py", line 247, in update
    lsd = np.array([location_deviation(pre, lab, lab_len, 'square') for pre, lab, lab_len in zip(pred, label, label_len)]).mean()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/LaDe-master/route_prediction/utils/eval.py", line 100, in location_deviation
    idx_2 = [pred.index(x) for x in label]
             ^^^^^^^^^^^^^
ValueError: 5 is not in list

Could you please help me? Thank you very much.

**Comment by wenhaomin** [comment]
**Possible reasons for the issue:** 
1. The version of `ortools` may differ from the required version. Please ensure you are using `ortools==6.8.5452`.
2. There might be an incorrect or modified version of `dataset.py`. Please verify that your script matches the original version.

If you have further questions or need assistance, feel free to contact via:

- **WeChat:** 13161826011
- **Email:** maoxiaowei@bjtu.edu.cn

**Comment by jiaziying** [comment]
Hi, thank you for your reply. ortools==6.8.5452 is no longer available for installation.
